services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=True
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  db:
    image: supabase/postgres:15.1.0  # 🔥 extension-packed beast
    ports:
      - "5432:5432"
    environment:
      - SUPABASE_DB: kitenga_db`
      SUPABASE SERVICE_ROLE: anon
      
      - POSTGRES_PASSWORD: postgres
      - POSTGRES_USER: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
networks:
  default:
    driver: bridge